[[libcrossterm]]
arch = "aarch64"
git-tree-sha1 = "5052d5f0c99942dbfbfa9327ee2170e43f8ced5e"
os = "macos"

    [[libcrossterm.download]]
    sha256 = "bd19243b3e6afbb5113fe786a2389810683d008e911ef117363574b255435514"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.4.0+0/libcrossterm.v0.4.0.aarch64-apple-darwin.tar.gz"
[[libcrossterm]]
arch = "aarch64"
git-tree-sha1 = "c885cb9a17256f65cfba1ea7a8ac244f40a6fc49"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "dbef8f91460cf9e647b90f8cc69ab4ea8896aac47010e6797d0bc3fd7de9509f"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.4.0+0/libcrossterm.v0.4.0.aarch64-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b3767e6c5c1c24849fe8c61175bfcefc5b9426e4"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "a073dae5254a0c25a12422ae2fe6a3336344d8e42f94fcce42f9874897b90bca"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.4.0+0/libcrossterm.v0.4.0.armv6l-linux-gnueabihf.tar.gz"
[[libcrossterm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "35dc989b20c622a13495bdc4f229834d70691d1c"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "b63abcf68cc24bf0c7b968cd9583ca15623d70433bc18dd5737cf71f5e8ef0d7"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.4.0+0/libcrossterm.v0.4.0.armv7l-linux-gnueabihf.tar.gz"
[[libcrossterm]]
arch = "i686"
git-tree-sha1 = "8eea31ac49f75150fddcdf99f67be4291534b876"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "15e2baaa330adb03d184dccfc1065b558ee9748a7fae63feabea9f8737a45b97"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.4.0+0/libcrossterm.v0.4.0.i686-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "powerpc64le"
git-tree-sha1 = "f5d5edbecafbe403ccc5eedaf345fa063131aa06"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "d37ae47188943dcfed028ad8390148d58bbdaf199345d2621c076baaccf4af3f"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.4.0+0/libcrossterm.v0.4.0.powerpc64le-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "c25374e629255111c720d5119101387fa470ecab"
os = "macos"

    [[libcrossterm.download]]
    sha256 = "4ca44d548f270b99db984d2a24c2d5b5c1eb3cb8dbfea138801e3ed800d55508"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.4.0+0/libcrossterm.v0.4.0.x86_64-apple-darwin.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "60df5fdaab2510835d66b8ecf92725ae4369ff01"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "cbae3b55e7d06349bed29b581287a96db41312af8650d9e29fa4fbda48914c80"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.4.0+0/libcrossterm.v0.4.0.x86_64-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "e77464e99f9aa756497f6f45eee79edb95dfa9ca"
os = "freebsd"

    [[libcrossterm.download]]
    sha256 = "dc2aa4a3369549ecdd2b6fe484986537933befcd904818f20634b342fd6c64cb"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.4.0+0/libcrossterm.v0.4.0.x86_64-unknown-freebsd.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "cdcb3aee9c22cea7e2bac2d69e1cca696ec8c996"
os = "windows"

    [[libcrossterm.download]]
    sha256 = "7baa492226d46156fbdd86bb167f274d9145edf8d04821b6e84da839ace56f0e"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.4.0+0/libcrossterm.v0.4.0.x86_64-w64-mingw32.tar.gz"
