[[libcrossterm]]
arch = "aarch64"
git-tree-sha1 = "ee411697f6ca3dac743e9e32497859dc345020f4"
os = "macos"

    [[libcrossterm.download]]
    sha256 = "67329b53240deefe50d4c4361da4c2739dc04852e03d148cf92d7f34748c34cf"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.8.0+0/libcrossterm.v0.8.0.aarch64-apple-darwin.tar.gz"
[[libcrossterm]]
arch = "aarch64"
git-tree-sha1 = "a21d68d65c95081768fb8859903133c763570b28"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "ebb631c16e6c2de2c82aaae95ccfe3cb83da51129327e02b39fd09e6d1edd9d9"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.8.0+0/libcrossterm.v0.8.0.aarch64-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cd9733f3ec426e98f997a4998fc22ea055f3c566"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "8642b535d1ac493b34b5f22684a9e4b61a47d3b2f8c911675c1a40d6d7599113"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.8.0+0/libcrossterm.v0.8.0.armv6l-linux-gnueabihf.tar.gz"
[[libcrossterm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ee42588b00e1d2148c212c2ea4efdbd8bd2bb42d"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "56c0ee78d2f2b32fc2f96be1187519704f45cbd18e7fe928deb7924cc5d435d1"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.8.0+0/libcrossterm.v0.8.0.armv7l-linux-gnueabihf.tar.gz"
[[libcrossterm]]
arch = "i686"
git-tree-sha1 = "8799ef5a398edc4d0bddc6c102109d0f399df080"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "f54ddc498fac489b0ca3badd2b9b1c11411039190fa3027f746f6704dbc3ddc3"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.8.0+0/libcrossterm.v0.8.0.i686-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "powerpc64le"
git-tree-sha1 = "4f72505e73837293575f91d75fd4f8c6976c414a"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "94ebf39bbf399585c01adc2c4d4f17862cad44cc05133d7a6502200509adac08"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.8.0+0/libcrossterm.v0.8.0.powerpc64le-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "81d0333d42475a8514b391f1cbcdebcc1e67f6e5"
os = "macos"

    [[libcrossterm.download]]
    sha256 = "f53b594f2e8ed4f8e53e128520eaa5282fc82b7dc7603766f46ab8b4fb5053e2"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.8.0+0/libcrossterm.v0.8.0.x86_64-apple-darwin.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "21425560b3529f1b77317099850565165fe41b45"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "4ece1a10ed4e88fc138843db94ae02a8374f3239fdf45785183fbba6570aa18c"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.8.0+0/libcrossterm.v0.8.0.x86_64-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "fb70cb4f3af39389c076dff58bcf9a60fe297773"
os = "freebsd"

    [[libcrossterm.download]]
    sha256 = "ede29144c0d8ed303e18f2243ee66b958e4eefb6d913cf2f5511d3f4fd05d8da"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.8.0+0/libcrossterm.v0.8.0.x86_64-unknown-freebsd.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "c969e700684d60e3d5f1717571d59a0f282e72fb"
os = "windows"

    [[libcrossterm.download]]
    sha256 = "d1314c5baed765e113ca687942c88e2da01d6b06fa8b891ab41d9d19a418f43b"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.8.0+0/libcrossterm.v0.8.0.x86_64-w64-mingw32.tar.gz"
