[[libcrossterm]]
arch = "aarch64"
git-tree-sha1 = "3517ceb90375062de8afdfb8c91e3bcc30e51519"
os = "macos"

    [[libcrossterm.download]]
    sha256 = "38f8df93a3d8d113782a46e6c40c730fca2c83f12ac56e52b6ef535f70bd9019"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.1+0/libcrossterm.v0.6.1.aarch64-apple-darwin.tar.gz"
[[libcrossterm]]
arch = "aarch64"
git-tree-sha1 = "2e5bdc9bd5df775cce1ffd4268009e68808f98ae"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "9e576ec7fdc7bc95fb5d36b05529e880f6ddb72f62ee34810095facf521ee4d1"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.1+0/libcrossterm.v0.6.1.aarch64-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a7e23cb41eb8a595977f334111d88454ab3d1573"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "cda7d32e76bb00b4d5a8e7af8c1161a262fe2650c2743e912ee40ec5640dec67"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.1+0/libcrossterm.v0.6.1.armv6l-linux-gnueabihf.tar.gz"
[[libcrossterm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2400c8dbc0b8644ec4567b38b1688b7dca433872"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "7aade3fad002b5a28d714ff5ba6ff1255cce79202d26c6db5b6600f2ea39f6e3"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.1+0/libcrossterm.v0.6.1.armv7l-linux-gnueabihf.tar.gz"
[[libcrossterm]]
arch = "i686"
git-tree-sha1 = "8104e4574ed3bdc3e3e2f9e5d7394da637ee3807"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "77df78674bf7330b8256e459e8305a8bb6c3e693354e343072030eb2a768455b"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.1+0/libcrossterm.v0.6.1.i686-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "powerpc64le"
git-tree-sha1 = "18dbc166dea6f9e1a2178397777d6901252d92e7"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "d1769ff200b2c0d4b37658815f95ed09f4d453ab41a8125e16fb9ee1e2471932"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.1+0/libcrossterm.v0.6.1.powerpc64le-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "eb9510a4938bb427c6d374bf87ec380bfefb8c8a"
os = "macos"

    [[libcrossterm.download]]
    sha256 = "1a9444d0dfeda9288ff2988c0a55fc2b3aa282f3d620162191c2fe3c77184483"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.1+0/libcrossterm.v0.6.1.x86_64-apple-darwin.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "8ebe93dd695aab0e148698852dea72068a630180"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "50331e2bf027efbee2ac9041912d2217309a6643cabfa302f542babeadc6b577"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.1+0/libcrossterm.v0.6.1.x86_64-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "cc011cc32d3e7bd0b89092f5be87f436c76bf042"
os = "freebsd"

    [[libcrossterm.download]]
    sha256 = "dd4c1db7d4dacd8020bdb9f863652eb15a1a77ba167185d7b19c66d5c2b021c1"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.1+0/libcrossterm.v0.6.1.x86_64-unknown-freebsd.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "a1085ea64137df0e5ad3ba58572f725a314b8e14"
os = "windows"

    [[libcrossterm.download]]
    sha256 = "08bc8e28fd1a6239bd9b737f0cdee614c154eb7cf7dabd8077456ce6b30d88e1"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.1+0/libcrossterm.v0.6.1.x86_64-w64-mingw32.tar.gz"
