[[libcrossterm]]
arch = "aarch64"
git-tree-sha1 = "51ee257b528f9d5f1d3079d072c249c67e528360"
os = "macos"

    [[libcrossterm.download]]
    sha256 = "14fa30bd69c87f349ffc6462f47f296efcb69ae24e7bd0f5d20b5639bd6556b3"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.2+0/libcrossterm.v0.6.2.aarch64-apple-darwin.tar.gz"
[[libcrossterm]]
arch = "aarch64"
git-tree-sha1 = "cb944b50a3cc15077f5f94b65fca4f24fbf1a940"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "66bfa506f133eeedf08db4109d27c986f40f615f6f6f2267e4071e5cd7c13ef2"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.2+0/libcrossterm.v0.6.2.aarch64-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fe1a03068b4e408c21cebfc32c0f8060c9ec4a45"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "9de8f91bfea0872f9594dd9a2f9b2e69e4ffe335dd32e7d7bfa7d735cb636e2f"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.2+0/libcrossterm.v0.6.2.armv6l-linux-gnueabihf.tar.gz"
[[libcrossterm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9235ede0270adb86ff057c701d76027ed8892707"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "7db8007f2950219c9da5380280bd9113c21bb734bd5ee387e1a02b79e5502b44"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.2+0/libcrossterm.v0.6.2.armv7l-linux-gnueabihf.tar.gz"
[[libcrossterm]]
arch = "i686"
git-tree-sha1 = "47fe6489c2c6eac4bd1ae6d58c6495b8ffa5f345"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "c893482cf0cd96c759da213dc875c9c8626be5a526fc8779072a13afca1ece10"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.2+0/libcrossterm.v0.6.2.i686-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "powerpc64le"
git-tree-sha1 = "f5a246fd459b3d50e620957a805b9cea1110ef1e"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "d7bf56867d3a6c9596440472acafd441555ec1d2cbfe8586e00e2fece93f4c0f"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.2+0/libcrossterm.v0.6.2.powerpc64le-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "dfe90f28acb8126277b090203684d946db01f4ed"
os = "macos"

    [[libcrossterm.download]]
    sha256 = "52f57ae1f938f73fa82e3d9f9bd91b4079b877981d02b29eac431f173047124c"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.2+0/libcrossterm.v0.6.2.x86_64-apple-darwin.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "27f6e8d99ad13b304e4b98a47c6a14909c8b99d2"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "302c80344c5e5a85fa1c44ed41be9a376a72276e0be550c500d9c9dceff43cd2"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.2+0/libcrossterm.v0.6.2.x86_64-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "03f5fe717e0dc119aa3fd07123f3ff3315c5d18d"
os = "freebsd"

    [[libcrossterm.download]]
    sha256 = "ab9d686bc2e18a712ae25fce3a78183fb6ec9d9d0397231fff024d444132d535"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.2+0/libcrossterm.v0.6.2.x86_64-unknown-freebsd.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "3506fb38f0df330c8ca6bbe77670d74524575e6c"
os = "windows"

    [[libcrossterm.download]]
    sha256 = "f7457b9dc281b603ae05c66098c36a68ec1cfc8b9a704f85054dd8ce692762d3"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.2+0/libcrossterm.v0.6.2.x86_64-w64-mingw32.tar.gz"
