[[libcrossterm]]
arch = "aarch64"
git-tree-sha1 = "b5ab53834e0ccf0a166fc35d039f4e8f1be6e0e8"
os = "macos"

    [[libcrossterm.download]]
    sha256 = "d98ffb0ea45d74d43f3c594957f87fb8f6bec17e05653c19ea43be2a6af99e4e"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.3+0/libcrossterm.v0.6.3.aarch64-apple-darwin.tar.gz"
[[libcrossterm]]
arch = "aarch64"
git-tree-sha1 = "d2ef33d2e8c498b97e41a731bdd4a700c8edeba3"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "a75575a6a2471c99fad2f123ef64d23c9029d121051a5cf3cbca5d3d87a0d5ea"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.3+0/libcrossterm.v0.6.3.aarch64-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "24da0ead236bf53f6a347095ae15bed25fcef16d"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "b8f8f9d603c0aa7222884a1adb312b6f5ba9d1133ca7e0a645e8039ce7cf8657"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.3+0/libcrossterm.v0.6.3.armv6l-linux-gnueabihf.tar.gz"
[[libcrossterm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "869c8bcedfb5330f0683aeac4da46c13efd45d33"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "e17dd2195766e8e1880bdf0272908f0255a2e34c1eacd0c0f5c696b108c1a85d"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.3+0/libcrossterm.v0.6.3.armv7l-linux-gnueabihf.tar.gz"
[[libcrossterm]]
arch = "i686"
git-tree-sha1 = "08b3ad2c11aee6ac43eb3442f960e4a5289d9055"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "c5b887f0d7055874922ba8d685f465e2054199cad4c03227f9b38b2129ba8600"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.3+0/libcrossterm.v0.6.3.i686-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "powerpc64le"
git-tree-sha1 = "eecf39c2ba6671cfc64821fe8feb849f2ea08f46"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "d3fe47f47cc1e25edeca5602c61db1d141abab63704704015c7579385a31fdb8"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.3+0/libcrossterm.v0.6.3.powerpc64le-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "ec4e25c471d9d259fd8f543de0c7677a9d7d0330"
os = "macos"

    [[libcrossterm.download]]
    sha256 = "b57cc2aa2628757be97ae8262e28c126a1bff538d0e344336db939827553e99f"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.3+0/libcrossterm.v0.6.3.x86_64-apple-darwin.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "31151bd76ec4d474424c8fb2549f4edbeb0d71c1"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "b4ba671961e93d89b4eacbb33467e13d70efeec4d3f280c75c8ee172ce69ba0b"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.3+0/libcrossterm.v0.6.3.x86_64-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "0d4cc1019821ceaed67d4f77ecacb3bb4d3d5849"
os = "freebsd"

    [[libcrossterm.download]]
    sha256 = "b7b0c11e9584d5dc63448778138ee89990d9bec61e2d0d7ab45ea22b7742c605"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.3+0/libcrossterm.v0.6.3.x86_64-unknown-freebsd.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "197e8e55f143a57b77df22d377601b496d6bb31c"
os = "windows"

    [[libcrossterm.download]]
    sha256 = "40061ba13a485cbf2b662159a9f9524b826455dc66f4c65139374854c03a45c0"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.3+0/libcrossterm.v0.6.3.x86_64-w64-mingw32.tar.gz"
