[[libcrossterm]]
arch = "aarch64"
git-tree-sha1 = "ed6d5b19b663ddfffb0595b61437ca3be713af80"
os = "macos"

    [[libcrossterm.download]]
    sha256 = "22135519256c3af20002bfed824e48ca037c70f8e0c3e2f160a674af790f3c2b"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.4+0/libcrossterm.v0.6.4.aarch64-apple-darwin.tar.gz"
[[libcrossterm]]
arch = "aarch64"
git-tree-sha1 = "d23679b331a1b952ddda682972713d7b876753e8"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "9af846933d60bf69566dfba0ed9f79c601a1ddb31f8eb3d10b44d8d50bb80fbb"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.4+0/libcrossterm.v0.6.4.aarch64-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1f5b6bc61ef77c6597d6386057c5cb19065b6615"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "efd4109e6d7ba94a9a2668fd2576fe8016d0d19734c5c02469279308db8ddc34"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.4+0/libcrossterm.v0.6.4.armv6l-linux-gnueabihf.tar.gz"
[[libcrossterm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2994133f195acb635e822fdeaae77aef0d33e9be"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "cfb2fe6b28615a3d4cb5df20f1cb798aa6d5094abf577053fe95b90d695caf0a"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.4+0/libcrossterm.v0.6.4.armv7l-linux-gnueabihf.tar.gz"
[[libcrossterm]]
arch = "i686"
git-tree-sha1 = "16e944505591a744244dc4e9831bf04da84fef24"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "5b5abad74a1f465a3a0e8080823332e151464f378b45095b5e9f0703ff533668"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.4+0/libcrossterm.v0.6.4.i686-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "powerpc64le"
git-tree-sha1 = "ce6d3c10eb0252b3abd2debe292824328026b811"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "f4f925e40aae23d0a5160d7828410feada00c8ee75b392837b75901d6af38c45"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.4+0/libcrossterm.v0.6.4.powerpc64le-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "9c01b95f5b776d9a6ecf6d60a34db649a4bb8e4b"
os = "macos"

    [[libcrossterm.download]]
    sha256 = "908ef44c1666a26a17f545c93f43c071334d62c639283741085ac37e5cae4ac5"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.4+0/libcrossterm.v0.6.4.x86_64-apple-darwin.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "505f0a7521ae59fa16138963ca6be8ffbb8b7b4d"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "15034bd88a30705e822544ecdfb6ef657771934bcb7425a82a2b20f999a488fb"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.4+0/libcrossterm.v0.6.4.x86_64-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "2058e3632c8ba2276a3847e956c9210981f937c7"
os = "freebsd"

    [[libcrossterm.download]]
    sha256 = "850e90580a6f432ccf4648ca92aa45f0dc8b3bb25efe1a959510d6969aeae776"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.4+0/libcrossterm.v0.6.4.x86_64-unknown-freebsd.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "1f180494feac8968751ae03c009350eb1152ed0a"
os = "windows"

    [[libcrossterm.download]]
    sha256 = "14d04bb1f4f54e5454d796da2f1f4cc03c7f4e47303aef6bcb2680b166140534"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.6.4+0/libcrossterm.v0.6.4.x86_64-w64-mingw32.tar.gz"
