[[libcrossterm]]
arch = "aarch64"
git-tree-sha1 = "20fbfdf516f06480bf2ff74d4ae800394725d073"
os = "macos"

    [[libcrossterm.download]]
    sha256 = "ea7da751c7280dee6fbb4bd4db81d2121cfc8d75a7497c832994ee2b5dc20372"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.3.0+0/libcrossterm.v0.3.0.aarch64-apple-darwin.tar.gz"
[[libcrossterm]]
arch = "aarch64"
git-tree-sha1 = "be189fa86429bb0b9e33090612ace92cfbc264db"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "49ffd0eb0bf3527b7b0b7cc54d9e22bc237bed1d42a2cd16f2cc44d5ca944ece"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.3.0+0/libcrossterm.v0.3.0.aarch64-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "76eb6d9b4218711da0850e7923a65eaa22d9e700"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "8ab8ae3a2c36eac4f6681183f0ee7484af7c4bb4a5d4b0ed684813fe803a1871"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.3.0+0/libcrossterm.v0.3.0.armv6l-linux-gnueabihf.tar.gz"
[[libcrossterm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94868f2fb18d058e5d9428ad11e915014c43b93b"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "89542145cc6ba629f345a5cd478044be8d5203bd63e6cec928c5b426d8351339"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.3.0+0/libcrossterm.v0.3.0.armv7l-linux-gnueabihf.tar.gz"
[[libcrossterm]]
arch = "i686"
git-tree-sha1 = "05cf1362b7c2f77ad5d6f99bc951a933b4a50b90"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "f7ab311d084c4321e05c06aabcc4531b12ed1a7e7ba4f17dbdff28e2ef9d200c"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.3.0+0/libcrossterm.v0.3.0.i686-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "powerpc64le"
git-tree-sha1 = "e427399325abd2bf63e9f17e5ad22f3312f8ecac"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "91b3597435df355a00e5a78800b91264d49ab84776090a84cbe69a92582bcebc"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.3.0+0/libcrossterm.v0.3.0.powerpc64le-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "3aa750c35ac11ee40ce37f817c5ec45841f24d58"
os = "macos"

    [[libcrossterm.download]]
    sha256 = "71c7e711a9fed58a6876f641a9b5f13465980eb4350c981d2650ad91987ca1e7"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.3.0+0/libcrossterm.v0.3.0.x86_64-apple-darwin.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "0ad76901778a375610185cb864abebc70f675eac"
libc = "glibc"
os = "linux"

    [[libcrossterm.download]]
    sha256 = "c133b427b54bcb29f81c9fc6af91619417c9df03d32e8806ef07b6d073cd1609"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.3.0+0/libcrossterm.v0.3.0.x86_64-linux-gnu.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "3390748ce53ec5c9f02c659232616bca317c5dfe"
os = "freebsd"

    [[libcrossterm.download]]
    sha256 = "5d730080be86783062a9d47e00c15331539e69480edd3a36b90baa00f1d6655c"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.3.0+0/libcrossterm.v0.3.0.x86_64-unknown-freebsd.tar.gz"
[[libcrossterm]]
arch = "x86_64"
git-tree-sha1 = "41ff6b56865603b280058f2d3796a4c2f386a0b2"
os = "windows"

    [[libcrossterm.download]]
    sha256 = "7f737e686f11d45b1b093b2f7d7c5c78ed7d215352e89db1c644347827e90af7"
    url = "https://github.com/JuliaBinaryWrappers/libcrossterm_jll.jl/releases/download/libcrossterm-v0.3.0+0/libcrossterm.v0.3.0.x86_64-w64-mingw32.tar.gz"
